# Generated by Django 5.2.16 on 2026-09-10 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=7)),
                ('userpsw', models.CharField(max_length=6)),
                ('role', models.CharField(blank=True, choices=[('merlin', 'merlin'), ('percival', 'percival'), ('morgana', 'morgana'), ('assassin', 'assassin'), ('loyal_servant', 'loyal_servant'), ('oberon', 'oberon'), ('mordred', 'mordred'), ('minion', 'minion')], default='', max_length=20)),
                ('on_vote', models.BooleanField(default=False)),
                ('voted', models.BooleanField(default=False)),
                ('result', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(max_length=6, unique=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('started', 'Started')], default='waiting', max_length=10)),
                ('phase', models.CharField(choices=[('normal', 'Normal'), ('build', 'Build'), ('quest', 'Quest')], default='normal', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='room.player')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='room.room'),
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('build', 'Build'), ('quest', 'Quest')], max_length=10)),
                ('round_no', models.IntegerField()),
                ('members', models.JSONField(default=list)),
                ('agree', models.IntegerField(default=0)),
                ('disagree', models.IntegerField(default=0)),
                ('ballots', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('builder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='room.player')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='room.room')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('room', 'userid')},
        ),
    ]
