# Generated by Django 5.2.16 on 2026-09-10 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
